In [24]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv('../BreastCancerWc.csv')
df

,Sample code number,Clump Thickness,Uniformity of Cell Size,Unifromity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nucleoli,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [26]:
df.shape

(699, 11)

In [27]:
df.columns

Index(['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size',
       'Unifromity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nucleoli', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [28]:
feature=['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size',
       'Unifromity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class']
feature

['Sample code number',
 'Clump Thickness',
 'Uniformity of Cell Size',
 'Unifromity of Cell Shape',
 'Marginal Adhesion',
 'Single Epithelial Cell Size',
 'Bland Chromatin',
 'Normal Nucleoli',
 'Mitoses',
 'Class']

In [29]:
df['Bare Nucleoli']=df['Bare Nucleoli'].replace('?','1')

In [45]:
df.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Unifromity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nucleoli                  0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [46]:
df['Bare Nucleoli'].unique()

array(['1', '10', '2', '4', '3', '9', '7', '5', '8', '6'], dtype=object)

In [31]:
def outliers(df_out, drop=False):
    for each in df_out.columns:
        ft=df_out[each]
        Q1=np.percentile(ft,25.)
        Q3=np.percentile(ft,75.)
        IQR=Q3-Q1
        outlier_step=IQR*1.5
        outliers=ft[~((ft>=Q1-outlier_step) & ft<=Q3+outlier_step)].index.tolist()
        if not drop:
            print('For the feature {},No of outliers is {}'.format(each,len(outliers)))
        if drop:
            df.drop(outliers, inplace=True,errors='ignore')
            print('Outliers from {} feature removed'.format(each))

In [32]:
outliers(df[feature])

For the feature Sample code number,No of outliers is 0
For the feature Clump Thickness,No of outliers is 0
For the feature Uniformity of Cell Size,No of outliers is 0
For the feature Unifromity of Cell Shape,No of outliers is 0
For the feature Marginal Adhesion,No of outliers is 0
For the feature Single Epithelial Cell Size,No of outliers is 0
For the feature Bland Chromatin,No of outliers is 0
For the feature Normal Nucleoli,No of outliers is 0
For the feature Mitoses,No of outliers is 0
For the feature Class,No of outliers is 0

In [33]:
outliers(df[feature],drop=True)

Outliers from Sample code number feature removed
Outliers from Clump Thickness feature removed
Outliers from Uniformity of Cell Size feature removed
Outliers from Unifromity of Cell Shape feature removed
Outliers from Marginal Adhesion feature removed
Outliers from Single Epithelial Cell Size feature removed
Outliers from Bland Chromatin feature removed
Outliers from Normal Nucleoli feature removed
Outliers from Mitoses feature removed
Outliers from Class feature removed

In [34]:
df

,Sample code number,Clump Thickness,Uniformity of Cell Size,Unifromity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nucleoli,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [36]:
df

,Sample code number,Clump Thickness,Uniformity of Cell Size,Unifromity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nucleoli,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [39]:
X=df.drop(['Class'],axis=1).values
y=df['Class']

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [41]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [42]:
model_NB=MultinomialNB()
model_NB.fit(X_train,y_train)

MultinomialNB()

In [43]:
y_pred=model.predict(X_test)
y_NB_pred=model_NB.predict(X_test)

In [44]:
print("Logistic regression accuracy:",metrics.accuracy_score(y_test,y_pred)*100)
print("Naive-Bayes accuracy:",metrics.accuracy_score(y_test,y_NB_pred)*100)

Logistic regression accuracy: 68.0952380952381
Naive-Bayes accuracy: 95.23809523809523